### ISSUE TITLE
Kits on SD card don't load

### ISSUE THREAD

**Issue by alt-bin-all** [johnhw/cardputer_drums#4]
On bonnethead 1.0.6 - kits on SD card don't load as expected. Each time the UI says "Loading Kit n" and then falls back to current kit.

Wav files were exported from Audacity. I have tried different combinations of sample rate and bit depth; 8K or 16K, 8bit-unsigned, 16bit-signed.

SD card looks like this, with duplicate files in 6/7/8/9 for testing purposes (and all invisible ._* mac files have been removed:

bonnethead/
-- kits/
---- base-6.kit/
-------- a.wav
-------- b.wav
-------- c.wav
-------- d.wav
-------- e.wav
-------- f.wav
-------- g.wav
-------- h.wav
-------- i.wav
-------- j.wav
---- base-7.kit
---- base-8.kit
---- base-9.kit
-- patterns/
-- render/
-- samples/

Arduino IDE 2.3.4
M5Cardputer 1.0.2
M5Unified 0.2.4
ArduinoJson 7.3.0
macOS 13.6.1

**Comment by johnhw** [comment]
Okay, I'll have a look. Two initial possibilities: the files are too large and it's aborting because of limited space for the samples; or the file formats are incorrect. There is a converter tool in sample_editor/index.html that will definitely generate wav files in the right format if you want to try that. 

However, I suspect it might be a size issue; there's only space for 160K of samples, so if the total size of the kit exceeds that it'll fail.

**Comment by alt-bin-all** [comment]
Thank you!
I don't think it's the file size, as my kits are all ~90KB (77,126 bytes). 

Unless there is a minimum block size thing with FAT32? Now that I look closer I can see the files totalling up to 77,126 bytes, but "328 KB on disk". I guess that's it :/

I'll try removing some samples and see if it loads the trimmed set.

**Comment by alt-bin-all** [comment]
So, no luck yet.

I used the included sample_editor to make a kit. I cleared the SD card anew and made a fresh `SD:/bonnethead/kits/base-5.kit` directory that included just a single sample; a.wav. I rebuilt the sketch, fresh install (Erase all Flash before Sketch upload) - and when I ran it I got the same behaviour as before; try to load any user kit, and it just falls-back to the previous one. 

One clarification; Is there any expectation/covention to follow regarding kit naming? So far I'm just naming them per the native-kits, +1; But I don't know if there can be gaps between numbering, or otherwise arbitrarily named; or indeed how a conflict between user/native kit-naming would play out.

FWIW The logs show "Failed to open file for reading: /bonnethead/kits/base-5.kit/a.wav", if that's remotely useful.


Separately, the built-in Kit_01 throws a few Out of Memory errors it self, right from a fresh build (and I have cleared/rebuilt a handful of times). It may be expected behaviour :)

No such problem with kits 02/03/04; who all make it past "Making Synth 25" without fail.

```
...
Making synth 14
Making synth 15
Making synth 16
Making synth 17
Making synth 18
Making synth 19
Making synth 20
Out of memory
Making synth 21
Out of memory
Making synth 22
Out of memory
Making synth 23
Out of memory
Making synth 24
Out of memory
Making synth 25
Out of memory
...
```

**Comment by johnhw** [comment]
Hmm. Odd. I've pushed a new version (1.0.7), though I don't see why it would have changed anything. I just recompiled and tested with a fresh blank SD, booted without problem. Kits 1-4 seem to be working without a crash (though it still generates out of memory errors for kit 1 -- it's too big for the current sample rate).

For kits, you can name them as anything 5-9a-z (so base-5.kit or base-d.kit). No requirement for consecutive numbering, and you can omit any of the individual samples in a kit. I've added a sample chiptune kit in `kits/` that should work correctly as kit d.

For ref, I'm using M5Cardputer 1.0.2, M5GFX 0.2.6, and M5Unified 0.2.4, so should be the same dev. env as you. I've removed the ArduinoJSON dep as it's not used anymore.

**Comment by alt-bin-all** [comment]
Thanks John, the demo kit is a great idea. I'll just use that for testing from now on.

I purchased a clean 8GB SD card, hoping that was the issue, but no luck so far.

I've updated to Bonnethead 1.0.7, cleaned out and re-installed M5Stack Boards 2.0.7 (tried the Latest build as well), and turned on Verbose logging. With the SD card **out** at reset/boot, I get the following:

```
[  1613][V][esp32-hal-periman.c:174] perimanSetPinBusExtraType(): Successfully set extra_type SD_SS for pin 12
[  1624][W][sd_diskio.cpp:175] sdCommand(): no token received
[  1730][W][sd_diskio.cpp:175] sdCommand(): no token received
[  1836][W][sd_diskio.cpp:175] sdCommand(): no token received
[  1941][E][sd_diskio.cpp:200] sdCommand(): Card Failed! cmd: 0x00
[  1947][W][sd_diskio.cpp:489] ff_sd_initialize(): GO_IDLE_STATE failed
[  1954][E][sd_diskio.cpp:761] sdcard_mount(): f_mount failed: (3) The physical drive cannot work
[  1963][W][sd_diskio.cpp:175] sdCommand(): no token received
[  2068][W][sd_diskio.cpp:175] sdCommand(): no token received
[  2174][W][sd_diskio.cpp:175] sdCommand(): no token received
[  2280][E][sd_diskio.cpp:200] sdCommand(): Card Failed! cmd: 0x00
[  2307][E][vfs_api.cpp:99] open(): /littlefs/startup.drm does not exist, no permits for creation
```
_full logs and board options attached, below_


And when I insert the card and initiate a kit-load op, I get:

`[249383][E][vfs_api.cpp:23] open(): File system is not mounted`


> **EDIT: just removed the line about booting-with-the-card-inserted still causing the boot-loop; it did (even with this new card), but right now it does not. YayI**

Any setting you'd recommend I fix or change?

<img width="460" alt="Image" src="https://github.com/user-attachments/assets/2e27f735-709d-4e04-ad73-0eff17a111ff" />

[20250224_2040__noSdCard.txt](https://github.com/user-attachments/files/18949851/20250224_2040__noSdCard.txt)

**Comment by johnhw** [comment]
Nothing that should affect the SD card: I'd disable Erase All Flash (otherwise you can't persist patterns) and I have the partition scheme for Flash set to "Default 4MB for SPIFFS" (and Flash size set to 4MB). But I'm pretty sure that's not relevant here

The SD card should be formatted FAT32, but I guess that is okay as you saw the default folders get created. 

But I see a problem -- I've assumed that the SD card is always inserted on boot; I don't reinitialise it on kit load. Does the kit load if the SD card is inserted at boot? I'll update the code to re-initialise on load anyway!

**Comment by alt-bin-all** [comment]
> Does the kit load if the SD card is inserted at boot?

I’m still getting stuck in a boot-loop when I launch with the SD card inserted, unfortunately - (also why I was testing with Erase All Flash turned on). So I cannot test that yet. But for now initialising the SD on load sounds like a good plan.

Additionally, I’ve just attached a Verbose log to the [boot-loop issue](https://github.com/johnhw/cardputer_drums/issues/3), which will hopefully give a bit more insight to what’s going on there.

Thanks!

**Comment by johnhw** [comment]
Commit ebd9a736112841ae3b3ab1f17dddb7ee41d0eef9 now initialises on each file op, and seems to cope with card insertion once booted. Thanks for the logs for the boot-loop, I'll investigate.
